spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/catalogdb}

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: INFO
    com.bookstore.catalog: DEBUG