name: Catalog Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'catalog-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'catalog-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./catalog-service

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    # Convert owner to lowercase since GHCR requires it
    - name: Prepare metadata
      id: meta
      run: |
        echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./catalog-service              # 👈 This is critical
        file: ./catalog-service/Dockerfile      # 👈 Explicitly point to the Dockerfile
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ghcr.io/${{ steps.meta.outputs.owner }}/catalog-service:latest
          ghcr.io/${{ steps.meta.outputs.owner }}/catalog-service:${{ github.sha }}

